flowchart TD
  zulip_zulip["Zulip / Zulip\n[TypeScript, JavaScript, Python, PostgreSQL]"]
  porukehnoog0bho1izd_l_checkout["PorUKEHNoOG0bho1iZD L / Checkout\n[TypeScript, JavaScript, Python, PostgreSQL]"]
  n_2026_02_14t22_26_41["2026 02 14T22:26:41"]
  case_studies_windborne_constellation["Case Studies / WindBorne Constellation"]
  original_screen_4_dark["Original / Screen 4 Dark"]
  images_navigation_tour_video_thumbnail["Images / Navigation Tour Video Thumbnail"]
  case_studies_alaska_balloon["Case Studies / Alaska Balloon"]
  original_screen_4["Original / Screen 4"]
  unused_cartoon["Unused / Cartoon"]
  education_interactive_messaging_night["Education / Interactive Messaging Night"]
  zulip_zulip -->|feeds| porukehnoog0bho1izd_l_checkout
  porukehnoog0bho1izd_l_checkout -->|feeds| n_2026_02_14t22_26_41
  n_2026_02_14t22_26_41 -->|feeds| case_studies_windborne_constellation
  case_studies_windborne_constellation -->|feeds| original_screen_4_dark
  original_screen_4_dark -->|feeds| images_navigation_tour_video_thumbnail
  images_navigation_tour_video_thumbnail -->|feeds| case_studies_alaska_balloon
  case_studies_alaska_balloon -->|feeds| original_screen_4
  original_screen_4 -->|feeds| unused_cartoon
  unused_cartoon -->|feeds| education_interactive_messaging_night
  porukehnoog0bho1izd_l_checkout -->|depends on| education_interactive_messaging_night